import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  manifest: '/manifest.json',
  title: "Charter Express",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="manifest" crossOrigin="use-credentials" href="/manifest.json" />
      </head>
      <body>{children}</body>
    </html>
  );
}
